spring.application.name=vestas_proj

spring.datasource.url=${MYSQL_DB_NAME}
spring.datasource.username=${MYSQL_DB_USER}
spring.datasource.password=${MYSQL_DB_PW}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
loan.late.fee=0.33
book.borrow.days=7